// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#SQQOPOOO`OPO'#C^OeOPO'#C`OjOPO'#CaOoOPO'#CbOOOO'#Ce'#CeOOOO'#Cc'#CcQQOPOOOtOPO,58xOyOPO,58zO!OOPO,58{OOOO,58|,58|OOOO-E6a-E6aOOOO1G.d1G.dOOOO1G.f1G.fOOOO1G.g1G.g",
  stateData: "!Z~ORSOYPO[QO]RO~ORWO~ORXO~ORYO~OZZO~OZ]O~OZ^O~OZ_O~O][YRY~",
  goto: "iYPPZPZZZ_PeTTOVQVOR[VTUOV",
  nodeNames: "⚠ Document Title Text Heading Subheading Paragraph",
  maxTerm: 13,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "%U~RVOYhYZ!PZshst!Ut;'Sh;'S;=`y<%lOh~mSR~OYhZ;'Sh;'S;=`y<%lOh~|P;=`<%lh~!UOZ~~!ZWR~OYhZphpq!sqshst#Wt;'Sh;'S;=`y<%lOh~!zSY~R~OYhZ;'Sh;'S;=`y<%lOh~#]WR~OYhZphpq#uqshst$Yt;'Sh;'S;=`y<%lOh~#|S[~R~OYhZ;'Sh;'S;=`y<%lOh~$_UR~OYhZphpq$qq;'Sh;'S;=`y<%lOh~$xS]~R~OYhZ;'Sh;'S;=`y<%lOh",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  tokenPrec: 51
})
